#!/bin/sh
echo "🔍 Running ESLint before commit..."
npm run lint

if [ $? -ne 0 ]; then
  echo "❌ ESLint failed. Commit aborted."
  exit 1
fi

echo "🧼 Running Prettier before commit..."
npx prettier --check .

if [ $? -ne 0 ]; then
  echo "❌ Prettier failed. Commit aborted."
  exit 1
fi

echo "✅ Lint and Prettier passed. Proceeding with commit."
